title: Statistics
first_name: Brock
last_name: Akerman
email:  Brock.Akerman@outlook.com
future: true

url: "http://BrockAkerman.github.io"
baseurl: "/BrockAkerman.github.io"

# Ensure posts use a standard date-based URL structure
permalink: /:year/:month/:day/:title/


paginate: 5 # Number of posts per page
paginate_path: "/page:num/"