title: Statistics
first_name: Brock
last_name: Akerman
email: Brock.Akerman@outlook.com
future: true

# Set baseurl to your project folder name
baseurl: "/BrockAkerman.github.io"   # If your site is in a subdirectory
url: "https://bakerman1982.github.io"  # Your GitHub Pages domain


#url: "https://BrockAkerman.github.io"
#baseurl: ""


# Ensure posts use a standard date-based URL structure
permalink: /:year/:month/:day/:title/

paginate: 5 # Number of posts per page
paginate_path: "/page:num/"

include:
  - "_projects"
